common:
    lid_topic:  "/livox/lidar"
    imu_topic:  "/livox/imu"
    time_sync_en: false         # ONLY turn on when external time synchronization is really not possible
    time_offset_lidar_to_imu: 0.0 # Time offset between lidar and IMU calibrated by other algorithms, e.g. LI-Init (can be found in README).
    # This param will take effect no matter what time_sync_en is. So if the time offset is not known exactly, please set as 0.0

preprocess:
    lidar_type: 1                # 1 for Livox serials LiDAR, 2 for Velodyne LiDAR, 3 for ouster LiDAR,
    scan_line: 6
    blind: 1
    point_filter_num: 1

mapping:
    acc_cov: 0.1
    gyr_cov: 0.1
    b_acc_cov: 0.0001
    b_gyr_cov: 0.0001
    fov_degree:    90
    det_range:     450.0
    extrinsic_est_en:  false      # true: enable the online estimation of IMU-LiDAR extrinsic
    extrinsic_T: [ 0.04165, 0.02326, -0.0284 ]
    extrinsic_R: [ 1, 0, 0,
                   0, 1, 0,
                   0, 0, 1]

publish:
    path_en:  true
    scan_publish_en:  true       # false: close all the point cloud output
    dense_publish_en: true       # false: low down the points number in a global-frame point clouds scan.
    scan_bodyframe_pub_en: true  # true: output the point cloud scans in IMU-body-frame

pcd_save:
    pcd_save_en: false
    interval: -1                 # how many LiDAR frames saved in each pcd file;
    # -1 : all frames will be saved in ONE pcd file, may lead to memory crash when having too much frames.

mesh:
    hole_every_n_frame: 5               # 每隔 n 帧一次hole_process
    angle_resolution: 0.25
    fov_horizon: 78
    fov_vertical_up: 39
    fov_vertical_down: 39
    r_kNN: 5                            # 最近邻计算特征值的框的边长
    depth_th_normal: 0.5                # 框内 点-中心点深度差 阈值
    eigenvalue_threshold: 0.0001        # 确定初始平面点的阈值
    angle_threshold: 10                 # 区域生长 角度相似性阈值 单位度
    depth_threshold: 0.03               # 区域生长 平面点法向距离阈值 单位m
    angle_th_spd: 10                    # 相似平面检测，法向角度阈值
    dis_th_spd: 0.03                    # 相似平面检测，沿法向距离阈值
    ptsNum_threshold: 40                # 平面点数量阈值
    dis_resolution: 0.1                 # 平面划分网格的边长
    grid_ptsNum_threshold: 4            # 确定网格为内部点的点数阈值
    ptsNum_decimate_threshold: 1000     # 点投影矩阵是否重新计算
    voxel_resolution: 0.2               # 非平面部分 体素边长
    points_minimum_scale: 0.05          # 非平面部分 任意两个点之间最小距离
    r_nonplane: 0.1                     # 非平面部分 最近邻查找距离阈值
    N_nonplane: 10                      # 非平面部分 拟合三角形的点数阈值
    max_pts_num: 15000                  # 原始点云数量整除该数进行降采样 TODO
    if_save_raw_points: false
    if_quadtree_decimate: true          # 是否进行四叉树简化
    if_gui: true                        # 是否显示gui
    if_debug: false
    ptcl_topic: "/cloud_registered"
    odo_topic: "/Odometry"
    ptcl_save_path: "/home/neo/output_onlinemesh"
    dataset_name: "r3live"


